import { createOptimizedPicture } from '../../scripts/aem.js';
import { domEl } from '../../scripts/dom-helpers.js';
import { getIndividualIcon } from '../../scripts/utils.js';

/**
* Generates a the media content in the card.
* @param {HTMLElement} div - The `div` element to be transformed into a card media section.
* @param {HTMLElement} container - The card wrapper the content should be in.
*/
function generateMedia( div, container ) {
	div.className = 'backdrop-card__media';
	const img = container.querySelector( 'picture' );
	const imgWrapper = domEl( 'div', { class: 'backdrop-card__img' }, img );
	div.append( imgWrapper );
}

/**
* Generates a the non-media content in the card.
* @param {HTMLElement} div - The `div` element to be transformed into a card media section.
* @param {HTMLElement} container - The card wrapper the content should be in.
*/
function generateContent( div, container ) {
	const button = div.querySelector( '.usa-button__wrap' );
	const buttonLink = button?.querySelector( 'a' );
	const buttonText = buttonLink?.title;
	const heading = div.querySelector( 'h2, h3, h4, h5, h6' );
	div.className = 'backdrop-card__body';
	let meta = '';
	const pTags = div.querySelectorAll( 'p:not(.usa-button__wrap)' );
	
	if ( pTags.length > 1 ) {
		meta = domEl( 'span', { class: 'usa-tag' }, div.querySelector( 'p' ).textContent );
		div.querySelector( 'p' ).remove(); // remove meta p tag after we grab it
	}
	
	// take out the fake button and put into its own container
	if ( button ) {
		const fakeButton = domEl( 'p', { class: 'usa-button usa-button--secondary', title: buttonText }, buttonText );
		const buttonWrap = domEl( 'div', { class: 'backdrop-card__footer' } );
		buttonWrap.append( fakeButton );
		button.remove();
		container.append( buttonWrap );
		getIndividualIcon( fakeButton, 'arrow_forward' );
	}

	// take out the heading and put into its own container
	if ( heading ) {
		const link = buttonLink.getAttribute( 'href' );
		const cardLink = domEl( 'a', { class: 'backdrop-card__link', href: link }, heading.textContent );
		heading.innerHTML = '';
		heading.classList.add( 'backdrop-card__heading' );
		heading.appendChild( cardLink );
		const headerWrap = domEl( 'div', { class: 'backdrop-card__header'}, meta, heading );
		container.prepend( headerWrap );
	}
}

/**
* Generates in the card.
* @param {HTMLElement} container - The card wrapper the content should be in. child of the li
*/
function generateWholeCard( container ) {
	[...container.children].forEach( ( div ) => {
		if ( div.querySelector( 'picture' ) ) {
			generateMedia( div, container );
		} else {
			generateContent( div, container );
		}
	} );
	
	const picture = container.querySelector( '.backdrop-card__media' );
	const heading = container.querySelector( '.backdrop-card__header' );
	const desc = container.querySelector( '.backdrop-card__body' );
	const footer = container.querySelector( '.backdrop-card__footer' );
	const content = domEl( 'div', { class: 'backdrop-card__content' }, heading, desc, footer );
	container.append( picture );
	container.append( content );
}

/**
* Takes override data and creates populated element that is the same as manual entries. This is critical for formatting.
* @param {object} overrideRow - The `overrideRow` is a filtered object returned from search-index.json.
*/
export function buildWithOverrideData( overrideRow, index=0 ) {
	const imgSrc = overrideRow.image;
	const CTA_TEXT = 'Read more';
	const row = domEl( 'div' );
	const mediaDiv = domEl( 'div' );

	if ( imgSrc ) {
		mediaDiv.append( createOptimizedPicture( imgSrc, overrideRow.title || '', false, [{ width: '800' }] ) );
	} else {
		mediaDiv.append( domEl( 'div', { class: 'backdrop-card__img' } ) );
	}
	row.append( mediaDiv );
	const contentDiv = domEl( 'div' );
	const metaText = ( Array.isArray( overrideRow.tags ) && overrideRow.tags[0] ) || overrideRow.publicationDate || '';
	contentDiv.append( domEl( 'p', {}, metaText ) );
	const headingId = 'header-' + index;	
	contentDiv.append( domEl( 'h3', { id: headingId }, overrideRow.title || '' ) );
	contentDiv.append( domEl( 'p', {}, overrideRow.description || '' ) );

	const href = overrideRow.path || '#';
	const link = domEl( 'a', { href: href, title: CTA_TEXT }, CTA_TEXT );
	contentDiv.append( domEl( 'p', { class: 'usa-button__wrap' }, link ) );

	row.append( contentDiv );
	return row;
}

/**
* Generates all content in the card
* @param {HTMLElement} block - The card grid generated by EDS
*/
export default async function decorate( block, override=[] ) {
	const ul = domEl( 'ul', { class: 'backdrop-card-group usa-list--unstyled' } );
	let rows;
	if ( override.length ) {
		rows = override.map( buildWithOverrideData );
	} else {
		rows = [...block.children];
	}

	const parent = block.parentElement;
	const layout = parent?.parentElement?.dataset?.layout;

	if ( layout ) {
		const values = layout.split( '/' );
		const colClass = [...parent.classList].find( c => c.startsWith( 'desktop:grid-col-' ) );
  
		if ( colClass ) {
			const value = parseInt( colClass.replace( 'desktop:grid-col-', '' ), 10 );
			const newGrid =
				value > 6
					? `grid-col-12 tablet:grid-col-12 desktop:grid-col-${Math.max( Number( values[0] ), Number( values[1] ) )}`
					: 'grid-col-12 tablet:grid-col-12 desktop:grid-col-12';

			parent.classList.remove( colClass );
			newGrid.split( ' ' ).forEach( c => parent.classList.add( c ) );
		}
	}
	rows.forEach( row => {
		const li = domEl( 'li', { class: 'backdrop-card' } );
		const cardContainer = domEl( 'div', { class: 'backdrop-card__container' } );

		// add all the table row contents into a li with a container wrapper inside
		while ( row.firstElementChild ) {
			cardContainer.append( row.firstElementChild );
			li.append( cardContainer );
		}

		generateWholeCard( cardContainer );
		ul.append( li );
	} );

	ul.querySelectorAll( 'picture > img' ).forEach( ( img ) => img.closest( 'picture' ).replaceWith( createOptimizedPicture( img.src, img.alt, false, [{ width: '800' }] ) ) );

	block.textContent = '';
	block.append( ul );
}
